name: ğŸ‘† Update social feed + gh data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
  
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: 8
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: â¬‡ Download depedencies
      run: |
        pnpm install
    - name: ğŸš§ Setup environment
      run: |
       pnpm run setup

    - name: ğŸ¶ Fetch gh static data
      run: |
        pnpm update-projects --access-token=${{ secrets.GITHUB_TOKEN }} --output-file=./static-data.log
        cat static-data.log
        git add .
        git commit -F ./static-data.log || true
        git push

#    - name: Fetch w/ Syndication ğŸš‚Junction
#      run: |
#        cd ./packages/social-feed/
#        pnpm fetch

#    - name: Output feed from Syndication ğŸš‚Junction
#      run: |
#        cd ./packages/social-feed/
#        pnpm output
